### ISSUE TITLE
Review SMASH! auto-suggest data and Solr queries to understand WHAM! next steps

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#111]
From notes (https://docs.google.com/document/d/1m9k55NIe6ZDVVBrHIiwjVWshcmSxNeAqXUhj8qXCwng/edit),
 Tim will take a look at what data he has already for autocomplete and the original Solr search results used to generate the JSON for the current SMASH! Implementation

**Comment by tworrall** [comment]
Review completed. Wrote a controller that does Solr queries than converts the results to JSON, which Huda's scripts can then use to build the autosuggest index.
