### ISSUE TITLE
Review and identify possibilities for autosuggest code packaging

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#113]
From https://docs.google.com/document/d/1m9k55NIe6ZDVVBrHIiwjVWshcmSxNeAqXUhj8qXCwng/edit, 

"John will further review Blacklight gemification/enginification in the context of autosuggest and also take a look at the existing Blacklight autocomplete feature. "

**Comment by jskinne3** [comment]
Packaged feature, named Nectarguide, to be reviewed is located at https://github.com/LD4P/nectarguide
