### ISSUE TITLE
Tests or evaluations for whether index meets use case criteria

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#118]
How do we assess whether the use cases have, in fact, been met?  Can we write tests that would allow us to verify that the index meets these use cases?

**Comment by hudajkhan** [comment]
Tim wrote RSpec tests which evaluate expected results based on queries.

**Comment by tworrall** [comment]
There are two sets of tests. The first tests whether the Solr results are what we expect; the second tests the contents of the response that is sent back to the autocomplete object and that comprises the items contained in the autosuggest display.
