### ISSUE TITLE
Ensure Discogs API terms of service are met for the demo

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#133]
Translating action items from https://wiki.lyrasis.org/display/LD4P3/2020-09-25+Cornell+LD4P3+Meeting+notes:
Make sure the live demo meets the Discogs API terms of service in terms of linking and back.

Note: We already do include a link to the main Discogs but would need to add the disclaimer they request. 
https://support.discogs.com/hc/en-us/articles/360009334593-API-Terms-of-Use

**Comment by tworrall** [comment]
I don't think the notice is required for the demo. The terms state that the terms are required if the application is "public-facing." We're not demoing a live application. Also, the notice doesn't have to be on the item view page (though the link does). It just needs to be somewhere on the application.
