### ISSUE TITLE
Create more balanced display for influences tab (on DASH! authors) 

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#141]
When an author has a much greater number of influences by (or for) than the other influence category, the display does not look balanced.  Using the option to see more of the relationships will help in providing an initial display that is more balanced and which can then be expanded.

**Comment by tworrall** [comment]
If both the influencers and influenced are less than 10, the entire chart is shown. Otherwise, a "View the complete chart" link is displayed, which displays the entire chart when the user clicks it.
