### ISSUE TITLE
Alternate forms: Clarify label and purpose/content

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#143]
From DASH! Usability results
"The label 'alternate forms' should be made clearer for end-users.  Additionally, the type of alternate names may be useful information to provide users.  For example, if names listed are the author’s name in different languages or if they are pseudonyms."

**Comment by tworrall** [comment]
For agents/authors, pseudonyms now get displayed in the info box at the top. The "Alternate forms" tab is now renamed "Reference info" and the alternate names display on that tab. This tab is geared more for librarians.
