### ISSUE TITLE
Connecting parallel searches from other sources

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#16]
Experimenting with querying DbPedia (initially) and now Wikidata in parallel with the keywords entered by the user.  Could use this for search suggestions and/or autocomplete suggestions while ensuring that suggestions tie back to what is actually in the catalog

**Comment by tworrall** [comment]
Have implemented a "related searches" feature in a blacklight-cornell instance. The search suggestions are pulled from DBpedia, Wikidata and the LoC subject heading authority. In some cases the suggestions are very good, in others confusing and not necessarily "related." Needs more review and more refinement, if possible.

**Comment by hudajkhan** [comment]
The initial part of this issue has been completed as far as connecting to searches.  The second part is to connect back to searches in the catalog (and see if results are possible)

**Comment by hudajkhan** [comment]
The second part is addressed in issue  #29 .
