### ISSUE TITLE
Create and execute script analyzing wikidata connections/title matches

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#20]
@tworrall has provided JSON output from production solr search index for 1000 results with OCLC work id facet fields populated.  The following information is encoded in the output: BIB ID, OCLC Work ID, and Title of work. 

Per our discussion, @jskinne3 will work on a script that:

- Iterates through this list of solr document info and for each item, 
    - Extracts OCLC work id
    - Executes a query against Wikidata to see if the work id will resolve to a Wikidata URI and to retrieve the label of the entity using the following SPARQL query:`
 "SELECT ?item ?itemLabel WHERE {
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P5331 [oclc work id].}" `
 where [oclc work id] should be replaced with the work id.  For example, for the work id 16007, the above query would look like   `SELECT ?item ?itemLabel WHERE {
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P5331 "16007".} `  
    - The query can be executed using a Curl or Wget command as explained here: https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#SPARQL_endpoint . The curl command from the command line for the above query would be  
      - > curl -i -H "Accept: application/json" "https://query.wikidata.org/sparql?format=json&query=SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7BSERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%3Fitem%20wdt%3AP5331%20%2216007%22.%7D%0A"
   - Retrieves the wikidata URI and the label from the resulting json and then, in a separate json output or file, generates the following mapping: bib id -> OCLC work id -> Wikidata URI -> bib label -> wikidata label . 
         - Output from the request will be of the form below.  If the json is parsed and stored in an object called output, the URI will be found at output.results.bindings[0].item.value and label will be output.results.bindings[0].itemLabel.value
        > {
  "head" : {
    "vars" : [ "item", "itemLabel" ]
  },
  "results" : {
    "bindings" : [ {
      "item" : {
        "type" : "uri",
        "value" : "http://www.wikidata.org/entity/Q3823816"
      },
      "itemLabel" : {
        "xml:lang" : "en",
        "type" : "literal",
        "value" : "The Closers"
      }
    } ]
  }
}
- Take the generated file/output from the above and share back with us.  The first analysis we could do is look at percentage of our OCLC work ids from our set that mapped to wikidata URIs.  An additional step may be to do quick automated comparisons between the title retrieved from wikidata and the bib record title.

**Comment by hudajkhan** [comment]
In addition to the above, which reviewed 1000 bib id- OCLC work facet pairs, it would be good to review https://github.com/ld4l/cul-oclc-works/blob/master/2016-01-08-subset/bib_work_pairs.dat.gz and generate all matches from wikidata based on this list.

**Comment by hudajkhan** [comment]
Ran the script but timeout issues prevented from running across the entire dataset.  Resulted in >27 matches to Wikidata.  We can use these matches as possible examples for demonstrating where links between bib catalog works and wikidata are possible.

**Comment by jskinne3** [comment]
Ran script over first 32,435 lines of the `bib_work_pairs.dat` concordance file (a little more than 5% of the file). Of those, Wikidata returned a URI/title in 54 cases. That is a hit rate of 0.17%, or one match per 600 lines.

The 54 matches are listed here: https://github.com/LD4P/discovery/blob/9e45a17275b0ab62dd3c26c6c6639ce1d6637eaa/scripts/catalog_compare/bib_work_pairs_compare_output_summary.txt
