### ISSUE TITLE
Update blacklight cornell example with derivative works/translations by retrieving wikidata URI dynamically

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#21]
For a specific example where a bib record OCLC work id match exists in Wikidata, can we dynamically (a) query Wikidata to get the matching Wikidata URI given a particular OCLC ID and (b) query Wikidata for related works such as editions/translations and derivative works and display in the right-hand column (right above where other formats may be appearing now) .

Derivative work query may be based on https://github.com/LD4P/discovery/blob/master/cornell-demos/search_app/app/assets/javascripts/integrateLinks.js#L261 and editions can be based on https://github.com/LD4P/discovery/blob/master/cornell-demos/search_app/app/assets/javascripts/integrateLinks.js#L313 .   The out of the box Blacklight view customization that corresponds to this code is https://github.com/LD4P/discovery/blob/master/cornell-demos/search_app/app/views/catalog/_show_sidebar.html.erb .

**Comment by tworrall** [comment]
I have this working, displaying both editions and derivative works from Wikidata. Finding works in the catalog that have a corresponding match in Wikidata isn't easy.

**Comment by hudajkhan** [comment]
Code has been merged into master.
