### ISSUE TITLE
Include Discogs information for item/ show view

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#25]
Tim will explore how to connect Discogs information back to an item record view and show information in the page (e.g. track listing). 

Possible approach: Look for title match on master and retrieve info if it exists.

For now, a text lookup/search (as initial step).
There may be links between artists in wikidata and in Discogs, and that could be explored further later.

**Comment by hudajkhan** [comment]
Substantial analysis work as part of this issue which should also be recorded/documented. 
Also have examples from Tracey/Jason for musical catalog items that don't have a lot of metadata which would benefit from bringing in Discogs info.

**Comment by hudajkhan** [comment]
Tim included multiple properties from Discogs into the item view, while also checking to see what the catalog item displayed to avoid displaying information from Discogs where the catalog already included this information.  Using the examples provided by Tracey and Jason, Tim also demoed what inclusion of Discogs would look like for those examples as well.  He also worked on integrating Wikidata information and enabling links to catalog items based on information retrieved from Discogs and Wikidata.

**Comment by tworrall** [comment]
The master_id from Discogs provided a way of linking to Wikidata, which provided some additional information about the work. Musical recordings in the catalog don't have work_ids, so the links back to the catalog had to be done with solr queries using the title.
