### ISSUE TITLE
Check wikidata works (derived/translations/notable) and check existence in catalog (using identifiers)

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#27]
For works retrieved from wikidata, are there equivalences between wikidata URIs and OCLC (or other sources) that allow retrieval of specific catalog results that match those identifiers?

**Comment by tworrall** [comment]
There are only two ways to link the derived and notable works back to the catalog. The first, using the OCLC work_ids, is very limited. Not all of the works in Wikidata have work_ids and only a small percentage of works in our catalog have them. Also, most of the derived works are of a type -- for example, films -- that do not have the work_ids in Wikidata. The other method is simply by doing a solr query using the title of the work (and potentially the author), but the query results here are inconsistent.

**Comment by tworrall** [comment]
There are only two ways to link the derived and notable works back to the catalog. The first, using the OCLC work_ids, is very limited. Not all of the works in Wikidata have work_ids and only a small percentage of works in our catalog have them. Also, most of the derived works are of a type -- for example, films -- that do not have the work_ids in Wikidata. The other method is simply by doing a solr query using the title of the work (and potentially the author), but the query results here are inconsistent.
