### ISSUE TITLE
Add "influenced" wikidata property for display in the knowledge panel

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#33]
Let's add "influenced" in addition to "influenced by" to display info in the knowledge panel being displayed currently. 

For reference, this is the line that asks for "influenced by" info:
https://github.com/LD4P/discovery/blob/master/cornell-catalog-demo/app/assets/javascripts/integrateLinks.js#L150

This is the function that executes the ajax request: 
https://github.com/LD4P/discovery/blob/master/cornell-catalog-demo/app/assets/javascripts/integrateLinks.js#L239

What we'd need to do is reverse the order of subject and object, since it doesn't seem like "influenced by" has an inverse property.  So, instead of asking 
?influencedBy wdt:P737 wikidataURI where wikidataURI is the wikidata URI for the knowledge panelentity, we'd be asking wikidataURI wdt:P737 ?influenced (or something) to get people who this wikidataURI influenced (or, in other words, who were influenced by this wikidataURI).

**Comment by jskinne3** [comment]
Now getInfluenced() and getInfluencedBy() functions both exist and both add text to the Knowledge Panel. They are largely duplicated code; however, so is a lot of the file. It would be nice to combine queries later.
