### ISSUE TITLE
Outgoing link icon

### ISSUE THREAD

**Issue by jskinne3** [LD4P/discovery#39]
Links out of blacklight should have an icon indicating that they are taking the browser away from the catalog

**Comment by jskinne3** [comment]
According to @tworrall this is done thusly:
```
<a href="...">External link <i class="fa fa-external-link"></i></a>
```
Since it involves modifying each link, I'll be waiting until some other knowledge panel changes are finished up to avoid conflicts and duplicated work.

**Comment by hudajkhan** [comment]
Included outbound link for wikidata and digital collection results in knowledge panel. Separate issue can be made if we want to do something similar for related/derived works later.
