### ISSUE TITLE
Put in ORDER BY clause into SPARQL queries for knowledge panel

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#40]
For the following functions in the knowledge panel code: getNotableWorks(wikidataURI), getPeopleInfluencedBy(wikidataURI), and getPeopleWhoInfluenced(wikidataURI), we should update the SPARQL query to order the results. 
For the first (notable works), @jskinne3 found number of site links is a property we could use to order notable works. We should put in a note so that's it is clear how they are ordered and perhaps at a later date, review user feedback. 
For the influences/influenced by list, we can order by the label.

**Comment by jskinne3** [comment]
Sort the results of `getPeopleInfluencedBy(wikidataURI)` and `getPeopleWhoInfluenced(wikidataURI)` alphabetically by whole name. Sort `getNotableWorks(wikidataURI)` by number of sitelinks (as a rough measure of "notability").

**Comment by jskinne3** [comment]
Pull request https://github.com/LD4P/discovery/pull/44 also pertains to this issue. Moving issue the the Review pile.
