### ISSUE TITLE
Work on expanding browse for subject/work in item view

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#69]
KPAOW! work included the Finnegan's wake example where "browse subjects" on the bottom could help see works/title-author combinations close to the item.  BAM! could extend this to include this display within the item view.

**Comment by tworrall** [comment]
A broader to narrower list of subjects now displays on the item view pages. It draws primarily on LCSH headings that are also in the catalog, but if a work has an OCLC work ID it gets some additional subject headings that way.
