### ISSUE TITLE
Explore Subject:era facet and how to set up a separate page bringing in era and linked info

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#70]
Setting up a separate page (utilizing a different controller/route e.g. /browseTemporal) as a starting point to bring in Subject:era FAST time periods from the catalog and bringing in FAST labels (and potentially other linked information).  This will allow us to explore what the data looks like before we discuss potential visualization options/connections back to catalog search.

**Comment by jskinne3** [comment]
Here is a PR of this feature in a working but unfinished state:https://github.com/LD4P/blacklight-cornell/pull/15
I wasn't sure where to go with it next. I am closing this issue.
