### ISSUE TITLE
Investigate possibilities for Discogs connections

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#76]
Are there possibilities for incorporating Discogs data in some aspects of browse?  This is a very general/broad question.

**Comment by hudajkhan** [comment]
Possibilities may exist but we may need to revisit this based on time requirements.

**Comment by tworrall** [comment]
I briefly looked into the possibility of displaying a discography of an artist's work using a timeline: with Sinatra, for example, the timeline would show his first album through his last. The discography would be limited to the works that are in the catalog. Ifthere had been more time for BAM, I would have pursued this, and it would be worth pursuing after Smash.
