### ISSUE TITLE
Explore syllabus reading lists into browse

### ISSUE THREAD

**Issue by jskinne3** [LD4P/discovery#78]

**Comment by jskinne3** [comment]
Blacklight UI is in pull request https://github.com/LD4P/blacklight-cornell/pull/3
And, temporary server is in repo https://github.com/jskinne3/cosine

**Comment by hudajkhan** [comment]
Per our discussion, adding in images from Wikidata plus author/title information to show in a carousel-like browse view for these items

**Comment by jskinne3** [comment]
Here's an update -- a pull request on code for CIP / field browse and improvements to item view browse list: https://github.com/LD4P/blacklight-cornell/pull/7

**Comment by jskinne3** [comment]
Above pull request merged by @hudajkhan, who also recommends changing Solr URL from hardcoded to Rails environment variable value. I'm working on that now.

**Comment by jskinne3** [comment]
Pull request that removes hardcoded Solr URLs:
https://github.com/LD4P/blacklight-cornell/pull/8

**Comment by jskinne3** [comment]
This feature has been tested and demoed. Here is a video documenting it: https://drive.google.com/open?id=1UxFQJksSeYZFlK1hoQSO1tP2aZ97Urtj

At some future time (particularly if the feature ends up in production) we may switch to Open Syllabus Project's official API, currently under construction: https://api.opensyllabus.org/
